# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CmdResponsePostRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'node_ids': 'list[str]',
        'cmd': 'int',
        'data': 'str',
        'timeout': 'int'
    }

    attribute_map = {
        'node_ids': 'node_ids',
        'cmd': 'cmd',
        'data': 'data',
        'timeout': 'timeout'
    }

    def __init__(self, node_ids=None, cmd=None, data=None, timeout=None):  # noqa: E501
        """CmdResponsePostRequest - a model defined in Swagger"""  # noqa: E501
        self._node_ids = None
        self._cmd = None
        self._data = None
        self._timeout = None
        self.discriminator = None
        if node_ids is not None:
            self.node_ids = node_ids
        if cmd is not None:
            self.cmd = cmd
        if data is not None:
            self.data = data
        if timeout is not None:
            self.timeout = timeout

    @property
    def node_ids(self):
        """Gets the node_ids of this CmdResponsePostRequest.  # noqa: E501


        :return: The node_ids of this CmdResponsePostRequest.  # noqa: E501
        :rtype: list[str]
        """
        return self._node_ids

    @node_ids.setter
    def node_ids(self, node_ids):
        """Sets the node_ids of this CmdResponsePostRequest.


        :param node_ids: The node_ids of this CmdResponsePostRequest.  # noqa: E501
        :type: list[str]
        """

        self._node_ids = node_ids

    @property
    def cmd(self):
        """Gets the cmd of this CmdResponsePostRequest.  # noqa: E501


        :return: The cmd of this CmdResponsePostRequest.  # noqa: E501
        :rtype: int
        """
        return self._cmd

    @cmd.setter
    def cmd(self, cmd):
        """Sets the cmd of this CmdResponsePostRequest.


        :param cmd: The cmd of this CmdResponsePostRequest.  # noqa: E501
        :type: int
        """

        self._cmd = cmd

    @property
    def data(self):
        """Gets the data of this CmdResponsePostRequest.  # noqa: E501


        :return: The data of this CmdResponsePostRequest.  # noqa: E501
        :rtype: str
        """
        return self._data

    @data.setter
    def data(self, data):
        """Sets the data of this CmdResponsePostRequest.


        :param data: The data of this CmdResponsePostRequest.  # noqa: E501
        :type: str
        """

        self._data = data

    @property
    def timeout(self):
        """Gets the timeout of this CmdResponsePostRequest.  # noqa: E501


        :return: The timeout of this CmdResponsePostRequest.  # noqa: E501
        :rtype: int
        """
        return self._timeout

    @timeout.setter
    def timeout(self, timeout):
        """Sets the timeout of this CmdResponsePostRequest.


        :param timeout: The timeout of this CmdResponsePostRequest.  # noqa: E501
        :type: int
        """

        self._timeout = timeout

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CmdResponsePostRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CmdResponsePostRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
