# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CmdResponseGetRequestRequests(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'request_id': 'str',
        'status': 'str',
        'device_status': 'float',
        'status_description': 'str',
        'response_data': 'CmdResponseGetRequestResponseData',
        'node_id': 'str',
        'request_timestamp': 'float',
        'response_timestamp': 'float',
        'expiration_timestamp': 'float'
    }

    attribute_map = {
        'request_id': 'request_id',
        'status': 'status',
        'device_status': 'device_status',
        'status_description': 'status_description',
        'response_data': 'response_data',
        'node_id': 'node_id',
        'request_timestamp': 'request_timestamp',
        'response_timestamp': 'response_timestamp',
        'expiration_timestamp': 'expiration_timestamp'
    }

    def __init__(self, request_id=None, status=None, device_status=None, status_description=None, response_data=None, node_id=None, request_timestamp=None, response_timestamp=None, expiration_timestamp=None):  # noqa: E501
        """CmdResponseGetRequestRequests - a model defined in Swagger"""  # noqa: E501
        self._request_id = None
        self._status = None
        self._device_status = None
        self._status_description = None
        self._response_data = None
        self._node_id = None
        self._request_timestamp = None
        self._response_timestamp = None
        self._expiration_timestamp = None
        self.discriminator = None
        if request_id is not None:
            self.request_id = request_id
        if status is not None:
            self.status = status
        if device_status is not None:
            self.device_status = device_status
        if status_description is not None:
            self.status_description = status_description
        if response_data is not None:
            self.response_data = response_data
        if node_id is not None:
            self.node_id = node_id
        if request_timestamp is not None:
            self.request_timestamp = request_timestamp
        if response_timestamp is not None:
            self.response_timestamp = response_timestamp
        if expiration_timestamp is not None:
            self.expiration_timestamp = expiration_timestamp

    @property
    def request_id(self):
        """Gets the request_id of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The request_id of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: str
        """
        return self._request_id

    @request_id.setter
    def request_id(self, request_id):
        """Sets the request_id of this CmdResponseGetRequestRequests.


        :param request_id: The request_id of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: str
        """

        self._request_id = request_id

    @property
    def status(self):
        """Gets the status of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The status of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this CmdResponseGetRequestRequests.


        :param status: The status of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def device_status(self):
        """Gets the device_status of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The device_status of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: float
        """
        return self._device_status

    @device_status.setter
    def device_status(self, device_status):
        """Sets the device_status of this CmdResponseGetRequestRequests.


        :param device_status: The device_status of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: float
        """

        self._device_status = device_status

    @property
    def status_description(self):
        """Gets the status_description of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The status_description of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: str
        """
        return self._status_description

    @status_description.setter
    def status_description(self, status_description):
        """Sets the status_description of this CmdResponseGetRequestRequests.


        :param status_description: The status_description of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: str
        """

        self._status_description = status_description

    @property
    def response_data(self):
        """Gets the response_data of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The response_data of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: CmdResponseGetRequestResponseData
        """
        return self._response_data

    @response_data.setter
    def response_data(self, response_data):
        """Sets the response_data of this CmdResponseGetRequestRequests.


        :param response_data: The response_data of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: CmdResponseGetRequestResponseData
        """

        self._response_data = response_data

    @property
    def node_id(self):
        """Gets the node_id of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The node_id of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this CmdResponseGetRequestRequests.


        :param node_id: The node_id of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def request_timestamp(self):
        """Gets the request_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The request_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: float
        """
        return self._request_timestamp

    @request_timestamp.setter
    def request_timestamp(self, request_timestamp):
        """Sets the request_timestamp of this CmdResponseGetRequestRequests.


        :param request_timestamp: The request_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: float
        """

        self._request_timestamp = request_timestamp

    @property
    def response_timestamp(self):
        """Gets the response_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The response_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: float
        """
        return self._response_timestamp

    @response_timestamp.setter
    def response_timestamp(self, response_timestamp):
        """Sets the response_timestamp of this CmdResponseGetRequestRequests.


        :param response_timestamp: The response_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: float
        """

        self._response_timestamp = response_timestamp

    @property
    def expiration_timestamp(self):
        """Gets the expiration_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501


        :return: The expiration_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :rtype: float
        """
        return self._expiration_timestamp

    @expiration_timestamp.setter
    def expiration_timestamp(self, expiration_timestamp):
        """Sets the expiration_timestamp of this CmdResponseGetRequestRequests.


        :param expiration_timestamp: The expiration_timestamp of this CmdResponseGetRequestRequests.  # noqa: E501
        :type: float
        """

        self._expiration_timestamp = expiration_timestamp

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CmdResponseGetRequestRequests, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CmdResponseGetRequestRequests):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
