# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sns_monthly_spending_limit': 'str',
        'is_sns_in_production': 'bool',
        'default_message_type': 'str'
    }

    attribute_map = {
        'sns_monthly_spending_limit': 'sns_monthly_spending_limit',
        'is_sns_in_production': 'is_sns_in_production',
        'default_message_type': 'default_message_type'
    }

    def __init__(self, sns_monthly_spending_limit=None, is_sns_in_production=None, default_message_type=None):  # noqa: E501
        """GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration - a model defined in Swagger"""  # noqa: E501
        self._sns_monthly_spending_limit = None
        self._is_sns_in_production = None
        self._default_message_type = None
        self.discriminator = None
        if sns_monthly_spending_limit is not None:
            self.sns_monthly_spending_limit = sns_monthly_spending_limit
        if is_sns_in_production is not None:
            self.is_sns_in_production = is_sns_in_production
        if default_message_type is not None:
            self.default_message_type = default_message_type

    @property
    def sns_monthly_spending_limit(self):
        """Gets the sns_monthly_spending_limit of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501


        :return: The sns_monthly_spending_limit of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._sns_monthly_spending_limit

    @sns_monthly_spending_limit.setter
    def sns_monthly_spending_limit(self, sns_monthly_spending_limit):
        """Sets the sns_monthly_spending_limit of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.


        :param sns_monthly_spending_limit: The sns_monthly_spending_limit of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :type: str
        """

        self._sns_monthly_spending_limit = sns_monthly_spending_limit

    @property
    def is_sns_in_production(self):
        """Gets the is_sns_in_production of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501


        :return: The is_sns_in_production of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :rtype: bool
        """
        return self._is_sns_in_production

    @is_sns_in_production.setter
    def is_sns_in_production(self, is_sns_in_production):
        """Sets the is_sns_in_production of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.


        :param is_sns_in_production: The is_sns_in_production of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :type: bool
        """

        self._is_sns_in_production = is_sns_in_production

    @property
    def default_message_type(self):
        """Gets the default_message_type of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501


        :return: The default_message_type of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :rtype: str
        """
        return self._default_message_type

    @default_message_type.setter
    def default_message_type(self, default_message_type):
        """Sets the default_message_type of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.


        :param default_message_type: The default_message_type of this GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration.  # noqa: E501
        :type: str
        """

        self._default_message_type = default_message_type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetRainMakerDeploymentDetailsPreRequisitePreRequisiteDetailsSnsConfiguration):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
