# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class GetNodeSharingRequestResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'sharing_requests': 'list[SharingDetails]',
        'next_request_id': 'str',
        'next_user_id': 'str'
    }

    attribute_map = {
        'sharing_requests': 'sharing_requests',
        'next_request_id': 'next_request_id',
        'next_user_id': 'next_user_id'
    }

    def __init__(self, sharing_requests=None, next_request_id=None, next_user_id=None):  # noqa: E501
        """GetNodeSharingRequestResponse - a model defined in Swagger"""  # noqa: E501
        self._sharing_requests = None
        self._next_request_id = None
        self._next_user_id = None
        self.discriminator = None
        if sharing_requests is not None:
            self.sharing_requests = sharing_requests
        if next_request_id is not None:
            self.next_request_id = next_request_id
        if next_user_id is not None:
            self.next_user_id = next_user_id

    @property
    def sharing_requests(self):
        """Gets the sharing_requests of this GetNodeSharingRequestResponse.  # noqa: E501


        :return: The sharing_requests of this GetNodeSharingRequestResponse.  # noqa: E501
        :rtype: list[SharingDetails]
        """
        return self._sharing_requests

    @sharing_requests.setter
    def sharing_requests(self, sharing_requests):
        """Sets the sharing_requests of this GetNodeSharingRequestResponse.


        :param sharing_requests: The sharing_requests of this GetNodeSharingRequestResponse.  # noqa: E501
        :type: list[SharingDetails]
        """

        self._sharing_requests = sharing_requests

    @property
    def next_request_id(self):
        """Gets the next_request_id of this GetNodeSharingRequestResponse.  # noqa: E501


        :return: The next_request_id of this GetNodeSharingRequestResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_request_id

    @next_request_id.setter
    def next_request_id(self, next_request_id):
        """Sets the next_request_id of this GetNodeSharingRequestResponse.


        :param next_request_id: The next_request_id of this GetNodeSharingRequestResponse.  # noqa: E501
        :type: str
        """

        self._next_request_id = next_request_id

    @property
    def next_user_id(self):
        """Gets the next_user_id of this GetNodeSharingRequestResponse.  # noqa: E501


        :return: The next_user_id of this GetNodeSharingRequestResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_user_id

    @next_user_id.setter
    def next_user_id(self, next_user_id):
        """Sets the next_user_id of this GetNodeSharingRequestResponse.


        :param next_user_id: The next_user_id of this GetNodeSharingRequestResponse.  # noqa: E501
        :type: str
        """

        self._next_user_id = next_user_id

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetNodeSharingRequestResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetNodeSharingRequestResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
