# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class OTACancelJob(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ota_job_id': 'str',
        'ota_job_name': 'str',
        'ota_image_id': 'str',
        'completed_count': 'int',
        'total_count': 'int',
        'triggered_timestamp': 'str',
        'cancelled_timestamp': 'str',
        'groups': 'str',
        'status': 'str',
        'archived': 'bool'
    }

    attribute_map = {
        'ota_job_id': 'ota_job_id',
        'ota_job_name': 'ota_job_name',
        'ota_image_id': 'ota_image_id',
        'completed_count': 'completed_count',
        'total_count': 'total_count',
        'triggered_timestamp': 'triggered_timestamp',
        'cancelled_timestamp': 'cancelled_timestamp',
        'groups': 'groups',
        'status': 'status',
        'archived': 'archived'
    }

    def __init__(self, ota_job_id=None, ota_job_name=None, ota_image_id=None, completed_count=None, total_count=None, triggered_timestamp=None, cancelled_timestamp=None, groups=None, status=None, archived=None):  # noqa: E501
        """OTACancelJob - a model defined in Swagger"""  # noqa: E501
        self._ota_job_id = None
        self._ota_job_name = None
        self._ota_image_id = None
        self._completed_count = None
        self._total_count = None
        self._triggered_timestamp = None
        self._cancelled_timestamp = None
        self._groups = None
        self._status = None
        self._archived = None
        self.discriminator = None
        if ota_job_id is not None:
            self.ota_job_id = ota_job_id
        if ota_job_name is not None:
            self.ota_job_name = ota_job_name
        if ota_image_id is not None:
            self.ota_image_id = ota_image_id
        if completed_count is not None:
            self.completed_count = completed_count
        if total_count is not None:
            self.total_count = total_count
        if triggered_timestamp is not None:
            self.triggered_timestamp = triggered_timestamp
        if cancelled_timestamp is not None:
            self.cancelled_timestamp = cancelled_timestamp
        if groups is not None:
            self.groups = groups
        if status is not None:
            self.status = status
        if archived is not None:
            self.archived = archived

    @property
    def ota_job_id(self):
        """Gets the ota_job_id of this OTACancelJob.  # noqa: E501


        :return: The ota_job_id of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._ota_job_id

    @ota_job_id.setter
    def ota_job_id(self, ota_job_id):
        """Sets the ota_job_id of this OTACancelJob.


        :param ota_job_id: The ota_job_id of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._ota_job_id = ota_job_id

    @property
    def ota_job_name(self):
        """Gets the ota_job_name of this OTACancelJob.  # noqa: E501


        :return: The ota_job_name of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._ota_job_name

    @ota_job_name.setter
    def ota_job_name(self, ota_job_name):
        """Sets the ota_job_name of this OTACancelJob.


        :param ota_job_name: The ota_job_name of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._ota_job_name = ota_job_name

    @property
    def ota_image_id(self):
        """Gets the ota_image_id of this OTACancelJob.  # noqa: E501


        :return: The ota_image_id of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._ota_image_id

    @ota_image_id.setter
    def ota_image_id(self, ota_image_id):
        """Sets the ota_image_id of this OTACancelJob.


        :param ota_image_id: The ota_image_id of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._ota_image_id = ota_image_id

    @property
    def completed_count(self):
        """Gets the completed_count of this OTACancelJob.  # noqa: E501


        :return: The completed_count of this OTACancelJob.  # noqa: E501
        :rtype: int
        """
        return self._completed_count

    @completed_count.setter
    def completed_count(self, completed_count):
        """Sets the completed_count of this OTACancelJob.


        :param completed_count: The completed_count of this OTACancelJob.  # noqa: E501
        :type: int
        """

        self._completed_count = completed_count

    @property
    def total_count(self):
        """Gets the total_count of this OTACancelJob.  # noqa: E501


        :return: The total_count of this OTACancelJob.  # noqa: E501
        :rtype: int
        """
        return self._total_count

    @total_count.setter
    def total_count(self, total_count):
        """Sets the total_count of this OTACancelJob.


        :param total_count: The total_count of this OTACancelJob.  # noqa: E501
        :type: int
        """

        self._total_count = total_count

    @property
    def triggered_timestamp(self):
        """Gets the triggered_timestamp of this OTACancelJob.  # noqa: E501


        :return: The triggered_timestamp of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._triggered_timestamp

    @triggered_timestamp.setter
    def triggered_timestamp(self, triggered_timestamp):
        """Sets the triggered_timestamp of this OTACancelJob.


        :param triggered_timestamp: The triggered_timestamp of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._triggered_timestamp = triggered_timestamp

    @property
    def cancelled_timestamp(self):
        """Gets the cancelled_timestamp of this OTACancelJob.  # noqa: E501


        :return: The cancelled_timestamp of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._cancelled_timestamp

    @cancelled_timestamp.setter
    def cancelled_timestamp(self, cancelled_timestamp):
        """Sets the cancelled_timestamp of this OTACancelJob.


        :param cancelled_timestamp: The cancelled_timestamp of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._cancelled_timestamp = cancelled_timestamp

    @property
    def groups(self):
        """Gets the groups of this OTACancelJob.  # noqa: E501


        :return: The groups of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._groups

    @groups.setter
    def groups(self, groups):
        """Sets the groups of this OTACancelJob.


        :param groups: The groups of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._groups = groups

    @property
    def status(self):
        """Gets the status of this OTACancelJob.  # noqa: E501


        :return: The status of this OTACancelJob.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this OTACancelJob.


        :param status: The status of this OTACancelJob.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def archived(self):
        """Gets the archived of this OTACancelJob.  # noqa: E501


        :return: The archived of this OTACancelJob.  # noqa: E501
        :rtype: bool
        """
        return self._archived

    @archived.setter
    def archived(self, archived):
        """Sets the archived of this OTACancelJob.


        :param archived: The archived of this OTACancelJob.  # noqa: E501
        :type: bool
        """

        self._archived = archived

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(OTACancelJob, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OTACancelJob):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
