# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TSAPINodeSuccessResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'node_id': 'str',
        'params': 'list[TSMeasureObject]',
        'next_id': 'str',
        'aggregate': 'str',
        'interval': 'str',
        'week_start': 'str',
        'timezone': 'str'
    }

    attribute_map = {
        'node_id': 'node_id',
        'params': 'params',
        'next_id': 'next_id',
        'aggregate': 'aggregate',
        'interval': 'interval',
        'week_start': 'week_start',
        'timezone': 'timezone'
    }

    def __init__(self, node_id=None, params=None, next_id=None, aggregate=None, interval=None, week_start=None, timezone=None):  # noqa: E501
        """TSAPINodeSuccessResponse - a model defined in Swagger"""  # noqa: E501
        self._node_id = None
        self._params = None
        self._next_id = None
        self._aggregate = None
        self._interval = None
        self._week_start = None
        self._timezone = None
        self.discriminator = None
        if node_id is not None:
            self.node_id = node_id
        if params is not None:
            self.params = params
        if next_id is not None:
            self.next_id = next_id
        if aggregate is not None:
            self.aggregate = aggregate
        if interval is not None:
            self.interval = interval
        if week_start is not None:
            self.week_start = week_start
        if timezone is not None:
            self.timezone = timezone

    @property
    def node_id(self):
        """Gets the node_id of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The node_id of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this TSAPINodeSuccessResponse.


        :param node_id: The node_id of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def params(self):
        """Gets the params of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The params of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: list[TSMeasureObject]
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this TSAPINodeSuccessResponse.


        :param params: The params of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: list[TSMeasureObject]
        """

        self._params = params

    @property
    def next_id(self):
        """Gets the next_id of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The next_id of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._next_id

    @next_id.setter
    def next_id(self, next_id):
        """Sets the next_id of this TSAPINodeSuccessResponse.


        :param next_id: The next_id of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._next_id = next_id

    @property
    def aggregate(self):
        """Gets the aggregate of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The aggregate of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._aggregate

    @aggregate.setter
    def aggregate(self, aggregate):
        """Sets the aggregate of this TSAPINodeSuccessResponse.


        :param aggregate: The aggregate of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._aggregate = aggregate

    @property
    def interval(self):
        """Gets the interval of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The interval of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._interval

    @interval.setter
    def interval(self, interval):
        """Sets the interval of this TSAPINodeSuccessResponse.


        :param interval: The interval of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._interval = interval

    @property
    def week_start(self):
        """Gets the week_start of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The week_start of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._week_start

    @week_start.setter
    def week_start(self, week_start):
        """Sets the week_start of this TSAPINodeSuccessResponse.


        :param week_start: The week_start of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._week_start = week_start

    @property
    def timezone(self):
        """Gets the timezone of this TSAPINodeSuccessResponse.  # noqa: E501


        :return: The timezone of this TSAPINodeSuccessResponse.  # noqa: E501
        :rtype: str
        """
        return self._timezone

    @timezone.setter
    def timezone(self, timezone):
        """Sets the timezone of this TSAPINodeSuccessResponse.


        :param timezone: The timezone of this TSAPINodeSuccessResponse.  # noqa: E501
        :type: str
        """

        self._timezone = timezone

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TSAPINodeSuccessResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TSAPINodeSuccessResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
