# coding: utf-8

"""
    API Definitions for RainMaker Backend Service

    This Swagger file provides the details about the RainMaker platform APIs.<br><br> There are two types of APIs supported by RainMaker - Unauthenticated and Authenticated.<br> The authenticated APIs are marked in the Swagger file, with a “lock” sign in front of them.<br> For the Unauthenticated APIs, there is no need to provide any authentication tokens in the HTTP header.<br> When the user logs in successfully, he receives access_token in the response. For the Authenticated APIs, this access_token needs to be passed in the \"Authorization\" HTTP header as the authentication token.<br> <br> <b>Note:</b><br><ul><li>RainMaker APIs do not support using double slashes after the resources or methods. Including a double slash goes against HTTP best practices. <br><li>The RainMaker APIs do not support following HTTP headers - data, verify and cookies.</ul>  # noqa: E501

    OpenAPI spec version: 1.1.17-fd1c887_2022-05-24T06:46
    Contact: esp-rainmaker-admin@espressif.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class UserOTAUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'status': 'str',
        'ota_available': 'bool',
        'description': 'str',
        'fw_version': 'str',
        'ota_job_id': 'str',
        'file_size': 'float'
    }

    attribute_map = {
        'status': 'status',
        'ota_available': 'ota_available',
        'description': 'description',
        'fw_version': 'fw_version',
        'ota_job_id': 'ota_job_id',
        'file_size': 'file_size'
    }

    def __init__(self, status=None, ota_available=None, description=None, fw_version=None, ota_job_id=None, file_size=None):  # noqa: E501
        """UserOTAUpdateRequest - a model defined in Swagger"""  # noqa: E501
        self._status = None
        self._ota_available = None
        self._description = None
        self._fw_version = None
        self._ota_job_id = None
        self._file_size = None
        self.discriminator = None
        if status is not None:
            self.status = status
        if ota_available is not None:
            self.ota_available = ota_available
        if description is not None:
            self.description = description
        if fw_version is not None:
            self.fw_version = fw_version
        if ota_job_id is not None:
            self.ota_job_id = ota_job_id
        if file_size is not None:
            self.file_size = file_size

    @property
    def status(self):
        """Gets the status of this UserOTAUpdateRequest.  # noqa: E501


        :return: The status of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this UserOTAUpdateRequest.


        :param status: The status of this UserOTAUpdateRequest.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def ota_available(self):
        """Gets the ota_available of this UserOTAUpdateRequest.  # noqa: E501


        :return: The ota_available of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._ota_available

    @ota_available.setter
    def ota_available(self, ota_available):
        """Sets the ota_available of this UserOTAUpdateRequest.


        :param ota_available: The ota_available of this UserOTAUpdateRequest.  # noqa: E501
        :type: bool
        """

        self._ota_available = ota_available

    @property
    def description(self):
        """Gets the description of this UserOTAUpdateRequest.  # noqa: E501


        :return: The description of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this UserOTAUpdateRequest.


        :param description: The description of this UserOTAUpdateRequest.  # noqa: E501
        :type: str
        """

        self._description = description

    @property
    def fw_version(self):
        """Gets the fw_version of this UserOTAUpdateRequest.  # noqa: E501


        :return: The fw_version of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._fw_version

    @fw_version.setter
    def fw_version(self, fw_version):
        """Sets the fw_version of this UserOTAUpdateRequest.


        :param fw_version: The fw_version of this UserOTAUpdateRequest.  # noqa: E501
        :type: str
        """

        self._fw_version = fw_version

    @property
    def ota_job_id(self):
        """Gets the ota_job_id of this UserOTAUpdateRequest.  # noqa: E501


        :return: The ota_job_id of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._ota_job_id

    @ota_job_id.setter
    def ota_job_id(self, ota_job_id):
        """Sets the ota_job_id of this UserOTAUpdateRequest.


        :param ota_job_id: The ota_job_id of this UserOTAUpdateRequest.  # noqa: E501
        :type: str
        """

        self._ota_job_id = ota_job_id

    @property
    def file_size(self):
        """Gets the file_size of this UserOTAUpdateRequest.  # noqa: E501


        :return: The file_size of this UserOTAUpdateRequest.  # noqa: E501
        :rtype: float
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size):
        """Sets the file_size of this UserOTAUpdateRequest.


        :param file_size: The file_size of this UserOTAUpdateRequest.  # noqa: E501
        :type: float
        """

        self._file_size = file_size

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(UserOTAUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, UserOTAUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
